# Generated by Django 2.1.2 on 2020-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_type', models.CharField(db_index=True, max_length=10)),
                ('chrom', models.CharField(db_index=True, max_length=10)),
                ('position', models.PositiveIntegerField(db_index=True)),
                ('Total_AC', models.PositiveIntegerField()),
                ('Total_AN', models.PositiveIntegerField()),
                ('Total_AF', models.FloatField()),
                ('KGP_AC', models.PositiveIntegerField()),
                ('KGP_AN', models.PositiveIntegerField()),
                ('KGP_AF', models.FloatField()),
                ('CN3270_AC', models.PositiveIntegerField()),
                ('CN3270_AN', models.PositiveIntegerField()),
                ('CN3270_AF', models.FloatField()),
                ('AFR_AC', models.PositiveIntegerField()),
                ('AFR_AN', models.PositiveIntegerField()),
                ('AFR_AF', models.FloatField()),
                ('AMR_AC', models.PositiveIntegerField()),
                ('AMR_AN', models.PositiveIntegerField()),
                ('AMR_AF', models.FloatField()),
                ('EAS_AC', models.PositiveIntegerField()),
                ('EAS_AN', models.PositiveIntegerField()),
                ('EAS_AF', models.FloatField()),
                ('EUR_AC', models.PositiveIntegerField()),
                ('EUR_AN', models.PositiveIntegerField()),
                ('EUR_AF', models.FloatField()),
                ('SAS_AC', models.PositiveIntegerField()),
                ('SAS_AN', models.PositiveIntegerField()),
                ('SAS_AF', models.FloatField()),
                ('CHB_and_CHS_1KGP_AC', models.PositiveIntegerField()),
                ('CHB_and_CHS_1KGP_AN', models.PositiveIntegerField()),
                ('CHB_and_CHS_1KGP_AF', models.FloatField()),
                ('CHB_AC', models.PositiveIntegerField()),
                ('CHB_AN', models.PositiveIntegerField()),
                ('CHB_AF', models.FloatField()),
                ('CHS_1KGP_AC', models.PositiveIntegerField()),
                ('CHS_1KGP_AN', models.PositiveIntegerField()),
                ('CHS_1KGP_AF', models.FloatField()),
                ('CDX_AC', models.PositiveIntegerField()),
                ('CDX_AN', models.PositiveIntegerField()),
                ('CDX_AF', models.FloatField()),
                ('CHN_AC', models.PositiveIntegerField()),
                ('CHN_AN', models.PositiveIntegerField()),
                ('CHN_AF', models.FloatField()),
                ('CHS_AC', models.PositiveIntegerField()),
                ('CHS_AN', models.PositiveIntegerField()),
                ('CHS_AF', models.FloatField()),
                ('JPT_AC', models.PositiveIntegerField()),
                ('JPT_AN', models.PositiveIntegerField()),
                ('JPT_AF', models.FloatField()),
                ('KHV_AC', models.PositiveIntegerField()),
                ('KHV_AN', models.PositiveIntegerField()),
                ('KHV_AF', models.FloatField()),
            ],
        ),
    ]
