# Generated by Django 2.1.2 on 2020-08-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
