# Generated by Django 2.1.2 on 2020-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='consequence',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sites',
            name='ensembl',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='gene',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sites',
            name='subfamily',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
