# Generated by Django 2.1.2 on 2020-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200827_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='consequence',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='ensembl',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='gene',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='subfamily',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
