# Generated by Django 2.1.2 on 2020-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200827_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='gene',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
