# Generated by Django 2.1.2 on 2020-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200827_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='LD_SNP',
            fields=[
                ('ass_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_index=True, max_length=100)),
                ('snp_id', models.CharField(db_index=True, max_length=50)),
                ('disease', models.CharField(db_index=True, max_length=1000)),
                ('pvalue', models.FloatField()),
            ],
        ),
    ]
