# Generated by Django 2.1.2 on 2021-05-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210523_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
