# Generated by Django 2.1.2 on 2021-07-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
