# Generated by Django 2.1.2 on 2021-10-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
