# Generated by Django 2.1.2 on 2021-10-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites',
        ),
    ]
